// Automatically generated from datasets/challan_fines.csv
export interface ChallanFine {
  violation_code: string;
  violation_description: string;
  applicable_section: string;
  act_name: string;
  vehicle_type: string;
  jurisdiction: string;
  first_offence_fine: string;
  repeat_offence_fine: string;
  imprisonment_first: string;
  imprisonment_repeat: string;
  compounding_fee: string;
  license_suspension: string;
  notes: string;
}

export const OFFLINE_CHALLAN_DB: ChallanFine[] = [
  {
    "violation_code": "GENERAL_OFFENCE",
    "violation_description": "General violation of any provision of the Act",
    "applicable_section": "Section 177",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "500",
    "repeat_offence_fine": "1500",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "500",
    "license_suspension": "",
    "notes": "Residual clause for offences not specifically covered"
  },
  {
    "violation_code": "DISOBEY_TRAFFIC_SIGN",
    "violation_description": "Disobeying traffic signs or signals",
    "applicable_section": "Section 177A",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "500",
    "repeat_offence_fine": "1500",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "500",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "UNAUTHORIZED_USE",
    "violation_description": "Use of vehicle without authority or permission",
    "applicable_section": "Section 178",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "5000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "5000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "DISOBEY_REGULATION",
    "violation_description": "Disobey regulations made by authority",
    "applicable_section": "Section 179",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "2000",
    "repeat_offence_fine": "4000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "2000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "NO_LICENCE",
    "violation_description": "Driving without a valid driving licence",
    "applicable_section": "Section 181",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "5000",
    "repeat_offence_fine": "5000",
    "imprisonment_first": "Up to 3 months",
    "imprisonment_repeat": "Up to 3 months",
    "compounding_fee": "5000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "DISQUALIFIED_DRIVING",
    "violation_description": "Driving despite disqualification",
    "applicable_section": "Section 182",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "10000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "Up to 3 months",
    "imprisonment_repeat": "Up to 3 months",
    "compounding_fee": "10000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "OVERSIZED_VEHICLE",
    "violation_description": "Driving oversized or overweight vehicle",
    "applicable_section": "Section 182A",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "transport",
    "jurisdiction": "national",
    "first_offence_fine": "5000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "5000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "OVERAGE_VEHICLE",
    "violation_description": "Driving an overage vehicle",
    "applicable_section": "Section 182B",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "5000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "5000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "NO_INSURANCE",
    "violation_description": "Driving without valid insurance",
    "applicable_section": "Section 196",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "2000",
    "repeat_offence_fine": "4000",
    "imprisonment_first": "Up to 3 months",
    "imprisonment_repeat": "Up to 3 months",
    "compounding_fee": "2000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "NO_HELMET",
    "violation_description": "Riding without protective headgear (helmet)",
    "applicable_section": "Section 194D",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "2-wheeler",
    "jurisdiction": "national",
    "first_offence_fine": "1000",
    "repeat_offence_fine": "2000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "1000",
    "license_suspension": "3 months (DL disqualified for repeat)",
    "notes": "ISI-standard helmet required"
  },
  {
    "violation_code": "NO_SEATBELT",
    "violation_description": "Driving without wearing seatbelt",
    "applicable_section": "Section 194B(1)",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "4-wheeler",
    "jurisdiction": "national",
    "first_offence_fine": "1000",
    "repeat_offence_fine": "1000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "1000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "SPEEDING",
    "violation_description": "Exceeding speed limit",
    "applicable_section": "Section 183",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "LMV",
    "jurisdiction": "national",
    "first_offence_fine": "1000",
    "repeat_offence_fine": "2000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "1000",
    "license_suspension": "",
    "notes": "For light motor vehicles"
  },
  {
    "violation_code": "SPEEDING_MEDIUM",
    "violation_description": "Exceeding speed limit - medium goods vehicle",
    "applicable_section": "Section 183",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "medium_goods",
    "jurisdiction": "national",
    "first_offence_fine": "2000",
    "repeat_offence_fine": "4000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "2000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "SPEEDING_HEAVY",
    "violation_description": "Exceeding speed limit - heavy vehicle / bus / transport",
    "applicable_section": "Section 183",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "heavy/transport",
    "jurisdiction": "national",
    "first_offence_fine": "3000",
    "repeat_offence_fine": "5000",
    "imprisonment_first": "Seizure of DL",
    "imprisonment_repeat": "Seizure of DL",
    "compounding_fee": "3000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "DANGEROUS_DRIVING",
    "violation_description": "Dangerous or rash driving",
    "applicable_section": "Section 184",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "5000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "Up to 1 year",
    "imprisonment_repeat": "Up to 2 years",
    "compounding_fee": "5000",
    "license_suspension": "",
    "notes": "Endangering life or property"
  },
  {
    "violation_code": "DRUNK_DRIVING",
    "violation_description": "Driving under influence of alcohol or drugs",
    "applicable_section": "Section 185",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "10000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "Up to 6 months",
    "imprisonment_repeat": "Up to 2 years",
    "compounding_fee": "10000",
    "license_suspension": "",
    "notes": "BAC limit: 30mg per 100ml blood. Non-compoundable in most states"
  },
  {
    "violation_code": "RACING",
    "violation_description": "Racing or speed trial without permission",
    "applicable_section": "Section 189",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "5000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "Up to 1 month",
    "imprisonment_repeat": "Up to 1 month",
    "compounding_fee": "5000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "MOBILE_PHONE",
    "violation_description": "Using mobile phone while driving",
    "applicable_section": "Section 184",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "5000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "Up to 6 months",
    "imprisonment_repeat": "Up to 1 year",
    "compounding_fee": "5000",
    "license_suspension": "",
    "notes": "Covered under dangerous driving"
  },
  {
    "violation_code": "SIGNAL_JUMP",
    "violation_description": "Jumping red signal / traffic light",
    "applicable_section": "Section 177A",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "1000",
    "repeat_offence_fine": "5000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "1000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "NO_PERMIT",
    "violation_description": "Driving transport vehicle without permit",
    "applicable_section": "Section 192A",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "transport",
    "jurisdiction": "national",
    "first_offence_fine": "10000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "Up to 6 months",
    "imprisonment_repeat": "Up to 6 months",
    "compounding_fee": "10000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "OVERLOADING_PAX",
    "violation_description": "Overloading of passengers",
    "applicable_section": "Section 194A",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "transport",
    "jurisdiction": "national",
    "first_offence_fine": "1000 per extra passenger",
    "repeat_offence_fine": "1000 per extra passenger",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "1000",
    "license_suspension": "",
    "notes": "Per extra passenger beyond capacity"
  },
  {
    "violation_code": "NO_REGISTRATION",
    "violation_description": "Driving unregistered vehicle",
    "applicable_section": "Section 192",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "5000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "Up to 1 year",
    "imprisonment_repeat": "Up to 1 year",
    "compounding_fee": "5000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "JUVENILE_DRIVING",
    "violation_description": "Allowing juvenile (minor) to drive",
    "applicable_section": "Section 199A",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "25000",
    "repeat_offence_fine": "25000",
    "imprisonment_first": "Up to 3 years",
    "imprisonment_repeat": "Up to 3 years",
    "compounding_fee": "",
    "license_suspension": "Registration cancelled, juvenile tried under JJ Act",
    "notes": "Guardian/owner held responsible"
  },
  {
    "violation_code": "NO_PUC",
    "violation_description": "Driving without Pollution Under Control certificate",
    "applicable_section": "Section 190(2)",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "10000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "Up to 6 months",
    "imprisonment_repeat": "Up to 6 months",
    "compounding_fee": "10000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "WRONG_SIDE",
    "violation_description": "Driving on wrong side of road",
    "applicable_section": "Section 184",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "5000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "Up to 6 months",
    "imprisonment_repeat": "Up to 1 year",
    "compounding_fee": "5000",
    "license_suspension": "",
    "notes": "Covered under dangerous driving"
  },
  {
    "violation_code": "NO_EMERGENCY_LANE",
    "violation_description": "Not giving way to emergency vehicles",
    "applicable_section": "Section 194E",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "10000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "10000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "AGGREGATOR_VIOLATION",
    "violation_description": "Violation by vehicle aggregator (ride-hailing)",
    "applicable_section": "Section 93",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "25000",
    "repeat_offence_fine": "50000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "25000",
    "license_suspension": "",
    "notes": "For Ola/Uber type aggregators"
  },
  {
    "violation_code": "NOISE_VIOLATION",
    "violation_description": "Excessive noise / modified silencer",
    "applicable_section": "Section 190(2)",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "1000",
    "repeat_offence_fine": "2000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "1000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "MODIFIED_VEHICLE",
    "violation_description": "Alteration of vehicle without approval",
    "applicable_section": "Section 191",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "5000",
    "repeat_offence_fine": "5000",
    "imprisonment_first": "Up to 1 year",
    "imprisonment_repeat": "Up to 1 year",
    "compounding_fee": "5000",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "HIT_AND_RUN",
    "violation_description": "Hit and run accident (causing injury/death)",
    "applicable_section": "Section 161",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "",
    "repeat_offence_fine": "",
    "imprisonment_first": "Up to 6 months (injury) / Up to 10 years (death)",
    "imprisonment_repeat": "",
    "compounding_fee": "",
    "license_suspension": "",
    "notes": "Non-compoundable; compensation via MACT"
  },
  {
    "violation_code": "OBSTRUCTION",
    "violation_description": "Causing obstruction to free flow of traffic",
    "applicable_section": "Section 177",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "500",
    "repeat_offence_fine": "1500",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "500",
    "license_suspension": "",
    "notes": ""
  },
  {
    "violation_code": "NUMBER_PLATE_VIOLATION",
    "violation_description": "Missing or improper number plate / fancy plate",
    "applicable_section": "Section 192",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "all",
    "jurisdiction": "national",
    "first_offence_fine": "5000",
    "repeat_offence_fine": "10000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "5000",
    "license_suspension": "",
    "notes": "HSRP plates mandatory"
  },
  {
    "violation_code": "TRIPLE_RIDING",
    "violation_description": "Riding with more than one pillion rider (triple riding) on a two-wheeler",
    "applicable_section": "Section 194C",
    "act_name": "MV Amendment Act 2019",
    "vehicle_type": "2-wheeler",
    "jurisdiction": "national",
    "first_offence_fine": "1000",
    "repeat_offence_fine": "1000",
    "imprisonment_first": "",
    "imprisonment_repeat": "",
    "compounding_fee": "1000",
    "license_suspension": "3 months",
    "notes": "Contravention of Section 128. DL disqualification for 3 months."
  }
];
